var express=require('express');
var exp=express();
var app=require('http').Server(exp);
var io = require('socket.io')(app);
var router=require('./router.js');
exp.set('view engine', 'ejs'); 
exp.use(express.static('../../public'));
exp.use('/user',router);
require('./socket.js').chat(io);
exports.exp=exp;
exports.app=app;
